permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: hiddaorear
  email: hiddaorear@outlook.com
  link: null
  weibo: null
  github: http://github.com/hiddaorear

# 站点信息
title: hiddaorear
description: hiddaorear
url: http://hiddaorear.github.io
rss_url: /pages/atom.xml
baseurl: /blog
highlighter: rouge

# avatar头像及Favicon
avatar: http://hiddaorear.github.io/assets/img/me.jpg
favicon: http://hiddaorear.github.io/assets/img/github.ico

# google analytics 设置
ga:
  url: hiddaorear.github.io

# disqus 设置
disqus:
  shortname: hiddaorear
