permalink: /:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author:
  name: hiddaorear
  email: hiddaorear@outlook.com
  github: https://github.com/hiddaorear

# 站点信息
title: 石下读书
description: 闲门向山路，深柳读书堂
url: https://hiddaorear.github.io
baseurl: /
highlighter: rouge
footer_content: "by 石下读书"
favicon_ico: "./assets/images/favicon.ico"
show_downloads: false

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# MathJax 数学公式支持
mathjax:
  on: true #是否启用
  per_page: true # 若只渲染单个页面，此选项设为false，页面内加入 mathjax: true