permalink: /:title.html
markdown: kramdown
pygments: true


markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author:
  name: hiddaorear
  email: hiddaorear@outlook.com
  link: null
  weibo: null
  github: https://github.com/hiddaorear

# 站点信息
title: 石下读书
description: hiddaorear
url: https://hiddaorear.github.io
baseurl: /
highlighter: rouge
